### ISSUE TITLE
Linter raises error when image name is used with string interpolation

### ISSUE THREAD

**Issue by looneytsci** [ByteriX/ImageLinter#1]
<img width="987" alt="Снимок экрана 2022-12-17 в 23 09 08" src="https://user-images.githubusercontent.com/82817544/208264355-ce4cc629-8648-4b66-b318-ec10a19f4388.png">

**Comment by sofbix** [comment]
can you change it to construction

Image(name: isOpen? "open" : "close") or add to ignore list "\(name)"?

**Comment by sofbix** [comment]
And you can just ignor, add in script to ignore list that's it
`let ignoredUndefinedImages: Set<String> = [
    "\\(name)"
]`
