### ISSUE TITLE
@x scale depending on Os type

### ISSUE THREAD

**Issue by NikKovIos** [ByteriX/ImageLinter#3]
Согласно эппл гайдланам https://developer.apple.com/design/human-interface-guidelines/images для iphone не нужно расширение x1, а для tvos x3. Гипотетически можно сократить размер бандла убирая эти размеры. 

![7B274B22-58AA-45F3-960E-3E040F97F793](https://github.com/ByteriX/ImageLinter/assets/16647690/7f73acee-6f16-44e5-9aef-8c10894e9f6e)

**Comment by sofbix** [comment]
полезное замечание, возьму в работу в ближайшее время. 
Спасибо.

**Comment by sofbix** [comment]
Проверте, пожалуйста, в текущей версии 1.7 должно заработать
