### ISSUE TITLE
How to fix "Image has floating size from scaled images"?

### ISSUE THREAD

**Issue by NikKovIos** [ByteriX/ImageLinter#7]
Есть ошибка:
activity_indicator.imageset/activity_indicator@3x.png:1:1 Image has floating size from scaled images. Real size is (80.0, 80.0) and scale = 3. Found for image 'activity_indicator'

![image](https://github.com/ByteriX/ImageLinter/assets/16647690/1ff0af4b-2a4b-4e60-b1b5-fa1e791e5263)
![image](https://github.com/ByteriX/ImageLinter/assets/16647690/4f826db8-2e1a-4a4d-938e-44367effe7c9)
![image](https://github.com/ByteriX/ImageLinter/assets/16647690/db6aaf06-3459-4513-a9f3-70dce71bc11f)

Не пойму в чём ошибка, как её исправить?

**Comment by sofbix** [comment]
а какой  размер у 1x? По идеи не может такого размера быть, 80 не делится на 3

**Comment by sofbix** [comment]
в 1.5.1 сделал уточнение, в чем заключается ошибка, кстати сделал поддержку сторибордов
