### ISSUE TITLE
Warning duplication for unused images

### ISSUE THREAD

**Issue by NikKovIos** [ByteriX/ImageLinter#8]
Когда ищу неиспользуемые картинки бывает такие воринги:

```
image_name.imageset/image_name.png
image_name.imageset/image_name.png:1:1 File unused from code. Found for image 'image_name'

image_name.imageset/image_name@2x.png
image_name.imageset/image_name@2x.png:1:1 File unused from code. Found for image 'image_name'

image_name.imageset/image_name@3x.png
image_name.imageset/image_name@3x.png:1:1 File unused from code. Found for image 'image_name'
```

Мне кажется на @2x и @3x скейлы не нужен дополнительный ворнинг. Достаточно только на основной scale.

**Comment by sofbix** [comment]
очень спорно, ну то есть, что если удалить из проекта image_name.png и оставить image_name@2x.png и image_name@3x.png, тогда что должно произойти?

**Comment by NikKovIos** [comment]
Тогда сделать только ворниг на image_name@2x.png. Если потом удалится image_name@2x.png, то сделать ворнинг на image_name@3x.png. Тоесть идея в том что если картинка не используется то не делать в логе дубликаты ворнинга, тк разработчик при виде ворнинга полезет в ассет и сделает изменения. Ворнинг как способ привлечь внимание разработчика. И в таком случае нет разницы между 1 ворнингом и 3мя, они несут функцию привлечения внимания и мотивации зайти, проверить ассет. 

Какая-то такая идея у меня)

**Comment by sofbix** [comment]
я понимаю что хочется красоты, но не будем превращать обычный линтер в исскуственный интелект. Есть файл - есть ворнинг, а ваше предложение - это уже кластеризация по типу ошибок и анализ самих ошибок, избыточная логика. Если бы была цель сделать звездолет который умней разработчиков, я бы так и заявил в описании, но моя цель это "simple script with minimum code", в будущем я возможно пересмотрю этот концепт и тогда возьмусь делать, пока не вижу смысла.

**Comment by sofbix** [comment]
Хотя ладно, там получается для всех файлов в цикле ворнинг бросается, можно и поправить

**Comment by NikKovIos** [comment]
Моё дело маленькое - описать боль и предложить вариант решения 🤷🏻‍♂️  :)

**Comment by sofbix** [comment]
пофиксил в 1.6.1, просьба проверить
