### ISSUE TITLE
Warnings in project

### ISSUE THREAD

**Issue by NikKovIos** [ByteriX/ImageLinter#9]
Может это важно, а может нет - если иметь файл линтёра в xcode и по нему будет проходиться статический анализатор - видны два ворнинга:

`print("\(firstArgument):\(#line): warning: images checking cancelled")`
images checking cancelled

`(1...result.numberOfRanges - 1).map { index in `
result of call to 'map' is unused

**Comment by sofbix** [comment]
Если все таки ворнинг сохранился с isEnabled = true, переоткройте пожалуйста. Но не забудте сделать "Clear All Issues" в XCode

**Comment by NikKovIos** [comment]
isEnabled = false, так что работает как ожидается 👍
